name: build

on:
  push:
    branches: 
        - master
        - development 
  pull_request:
    branches: 
        - master
        - development 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup token file
      run: mv /home/runner/work/Botcatmaxy/Botcatmaxy/src/BotCatMaxy/Properties/Tokens.targets.template /home/runner/work/Botcatmaxy/Botcatmaxy/src/BotCatMaxy/Properties/Tokens.targets
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
