name: .NET

on:
  push:
    branches: 
        - master
        - development 
  pull_request:
    branches: 
        - master
        - development 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        source-url: https://www.myget.org/F/discord-net/api/v3/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup 
      run: move /home/runner/work/Botcatmaxy/Botcatmaxy/BotCatMaxy/Properties/Tokens.targets.template /home/runner/work/Botcatmaxy/Botcatmaxy/BotCatMaxy/Properties/Tokens.targets
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
